

This is RAxML-Light version 1.0.5 released by Alexandros Stamatakis in June 2011.


Alignment has 783 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 0.78%

RAxML rapid hill-climbing mode

Using 3 distinct models/data partitions with joint branch length optimization


All free model parameters will be estimated by RAxML
GAMMA model of rate heteorgeneity, ML estimate of alpha-parameter

Partition: 0
Alignment Patterns: 298
Name: p1
DataType: AA
Substitution Matrix: WAG
Fixed Base Frequencies:



Partition: 1
Alignment Patterns: 89
Name: p2
DataType: AA
Substitution Matrix: WAG
Fixed Base Frequencies:



Partition: 2
Alignment Patterns: 396
Name: p3
DataType: AA
Substitution Matrix: JTT
Fixed Base Frequencies:




RAxML was called as follows:

./raxmlLight-PTHREADS -T 4 -t workin/RAxML_parsimonyTree.START -s workin/prot.phy -m PROTGAMMAWAG -q workin/partitionFile.txt -n Q 


Memory Saving Option: DISABLED
