#!/bin/bash

#try to implement all raxml models for seq-gen and update number of models
NUM_MODELS=7
RAXML_MODELS=(DAYHOFF DCMUT JTT MTREV WAG RTREV CPREV VT BLOSUM62 MTMAM LG MTART MTZOA PMB HIVB HIVW JTTDCMUT FLU GTR)
SEQGEN_MODELS=(JTT WAG PAM BLOSUM MTREV CPREV45 MTART)
TREEFILE=example.tree
NUM_CORES=48
MIN_LENGTH=150
MAX_LENGTH=500
declare -a models lengths

PARTFILE=part

#simulate n independent partitions with seqgen

touch $PARTFILE
cat /dev/null > $PARTFILE

for i in `seq 1 $1`;
do
	lengths[$i]=$(($RANDOM % ($MAX_LENGTH-$MIN_LENGTH) + $MIN_LENGTH))
	models[$i]=$(($RANDOM % $NUM_MODELS))
done

pos=1
for i in `seq 01 $1`;
do
#	echo seq-gen -l${lengths[$i]} -m${SEQGEN_MODELS[${models[$i]}]} $TREEFILE
	printf -v var %02d $i
	echo $var
	seq-gen -l${lengths[$i]} -m${SEQGEN_MODELS[${models[$i]}]} $TREEFILE > $var.phy
	echo "${SEQGEN_MODELS[${models[$i]}]}, part${i} = 1 - ${lengths[$i]}" > $var.part
	s=$pos
#	echo ${lengths[$i]}
	pos=$(($pos + ${lengths[$i]}))
	e=$pos
	pos=$((pos + 1))
	echo "${SEQGEN_MODELS[${models[$i]}]}, part${i} = ${s} - ${e}" >> $PARTFILE
done
 

#	glue together phylip files contained in this folder
phymod --glue .

#compute parsimony start tree


#compute model assignments using different search strategies
#exhaustive
#raxmlLight-PTHREADS -T $NUM_CORES -t RAxML_parsimonyTree.START -s $1.phy -m PROTGAMMAWAG -q $1.part -n exhaustive -l
#unlinked
#raxmlLight-PTHREADS -T $NUM_CORES -t RAxML_parsimonyTree.START -s $1.phy -m PROTGAMMAWAG -q $1.part -n unlinked -M


#	check if correct mapping of models was determined (if so, good, but chek the rest anyway)
#phymod
#	finally compute the tree for each modelassignment
#raxml hpc
#	integrate trees into one file to pas to raxml again for Robinson-Foulds distance

#afterwards, compare the trees to each other, plus the true tree
#raxml -f r -z [Treefile]
