#!/bin/bash
#create indelible config file, run and afterwards test everything


#simulate n independent partitions with seqgen
seq-gen 
#	glue together both phylip and partition file
phymod --glue

#compute model assignments using different search strategies
raxml-Light
#	check if correct mapping of models was determined (if so, good, but chek the rest anyway)
phymod
#	finally compute the tree for each modelassignment
raxml hpc
#	integrate trees into one file to pas to raxml again for Robinson-Foulds distance

#afterwards, compare the trees to each other, plus the true tree
reaxml -f r -z [Treefile]
